(* Do IO exceptions get converted? (should print nothing.) *)

#load "libsocket"

open Socket

let dummy =
  let sock = socket () in
  try bind sock 3; failwith "bug: didn't raise!" with
  | IOError _ -> ()
